name: darkwing
version: 0.0.1
environment:
  sdk: '>=2.7.1 <3.0.0'
dependencies:
  angular: ^5.3.1
  angular_components: ^0.13.0
  angular_forms: ^2.1.2
  angular_router: ^2.0.0-alpha+22
  logging: ^0.11.3
dev_dependencies:
  build_runner: ^1.8.0
  build_test: ^0.10.12+1
  build_web_compilers: ^2.9.0
  sass_builder: ^2.1.3
