version: '3'

volumes:
  db_data: {}

services:
  web:
    network_mode: host
    image: nginx:1.15
    container_name: darkwing-dev-web
    volumes:
      - "${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "${PWD}/server.crt:/etc/nginx/server.crt"
