version: '3'

volumes:
  db_data: {}

services:
  mongo:
    image: mongo
    container_name: darkwing-dev-mongo
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - db_data:/data/db
  web:
    image: nginx:1.15
    container_name: darkwing-dev-web
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    volumes:
      - "${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "${PWD}/server.crt:/etc/nginx/server.crt"
